import type { FleetCategory } from "../types"

export const fleet: readonly FleetCategory[] = [
  {
    id: "premium-vip-2026",
    name: "باص بريميوم VIP",
    yearLabel: "2026",
    seatsLabel: "18 + 1 + 1",
    summary:
      "اكتشف قمة الراحة والفخامة في حافلاتنا الجديدة، المزودة بمقاعد مساج مع التدفئة والتبريد لتجربة سفر مثالية.",
    amenities: [
      "مقاعد مساج",
      "مقاعد تبريد",
      "مقاعد تسخين",
      "منافذ شحن USB Type-C",
      "شبكة واي فاي",
      "نظام كاميرات مراقبة",
      "نظام الصوت",
      "شاشات عرض",
      "ثلاجة تبريد",
      "إضاءة مميزة",
      "حمام / دورة مياه",
      "ستائر فاخرة",
      "وسائل السلامة",
      "أنظمة فرامل متقدمة ABS",
      "نظام تحديد المواقع GPS",
    ],
    coverImage: "/fleet/premium-vip-2026/exterior/pv-col.webp",
    exteriorImages: [
      "/fleet/premium-vip-2026/exterior/pv-out-1.webp",
      "/fleet/premium-vip-2026/exterior/pv-out-2.webp",
      "/fleet/premium-vip-2026/exterior/pv-out-3.webp",
      "/fleet/premium-vip-2026/exterior/pv-out-4.webp",
      "/fleet/premium-vip-2026/exterior/pv-out-5.webp",
      "/fleet/premium-vip-2026/exterior/pv-out-6.webp",
    ],
    interiorImages: [
      "/fleet/premium-vip-2026/interior/pv-in-1.webp",
      "/fleet/premium-vip-2026/interior/pv-in-2.webp",
      "/fleet/premium-vip-2026/interior/pv-in-3.webp",
      "/fleet/premium-vip-2026/interior/pv-in-4.webp",
    ],
    images: ["/fleet/premium-vip-2026/exterior/pv-col.webp"],
    interactive: true,
  },
  {
    id: "vip-2026",
    name: "باص VIP",
    yearLabel: "2026",
    seatsLabel: "28 + 1 + 1",
    summary:
      "مقاعد VIP قابلة للتعديل والتحريك تمنحك حرية اختيار وضعية الجلوس المثالية لرحلة أكثر راحة.",
    amenities: [
      "مقاعد VIP فاخرة",
      "شبكة واي فاي",
      "نظام كاميرات مراقبة",
      "منافذ شحن USB",
      "إضاءة مميزة",
      "ثلاجة تبريد",
      "نظام الصوت",
      "حمام / دورة مياه",
      "شاشات عرض",
      "تكييف مناسب للأجواء",
      "ستائر فاخرة",
      "وسائل السلامة",
      "أنظمة فرامل متقدمة ABS",
      "نظام تحديد المواقع GPS",
    ],
    coverImage: "/fleet/vip-2026/cover.webp",
    exteriorImages: ["/fleet/vip-2026/cover.webp"],
    interiorImages: [],
    images: ["/fleet/vip-2026/cover.webp"],
  },
  {
    id: "coach-2025-2026",
    name: "كوتش باص",
    yearLabel: "2025 – 2026",
    seatsLabel: "49 + 1 + 1",
    summary:
      "نخدم الحجاج والمعتمرين بأسطول مجهز وفق أعلى معايير الجودة والسلامة.",
    amenities: [
      "مقاعد جلد فاخرة",
      "شبكة واي فاي",
      "نظام كاميرات مراقبة",
      "منافذ شحن USB",
      "إضاءة مميزة",
      "ثلاجة تبريد",
      "نظام الصوت",
      "حمام / دورة مياه",
      "شاشات عرض",
      "تكييف مناسب للأجواء",
      "ستائر فاخرة",
      "وسائل السلامة",
      "أنظمة فرامل متقدمة ABS",
      "نظام تحديد المواقع GPS",
    ],
    coverImage: "/fleet/coach-2025-2026/cover.webp",
    exteriorImages: ["/fleet/coach-2025-2026/cover.webp"],
    interiorImages: [],
    images: ["/fleet/coach-2025-2026/cover.webp"],
  },
  {
    id: "city-2024",
    name: "سيتي باص",
    yearLabel: "2024",
    seatsLabel: "45 + 1",
    summary:
      "شبكة نقل عصرية مصممة لتلبية متطلبات المدينة وتسهيل حركة الركاب بكفاءة عالية.",
    amenities: [
      "نظام كاميرات مراقبة",
      "مقاعد جلد فاخرة",
      "ستائر فاخرة",
      "وسائل السلامة",
      "أنظمة فرامل متقدمة ABS",
      "نظام تحديد المواقع GPS",
      "تكييف مناسب للأجواء",
    ],
    coverImage: "/fleet/city-2024/cover.webp",
    exteriorImages: ["/fleet/city-2024/cover.webp"],
    interiorImages: [],
    images: ["/fleet/city-2024/cover.webp"],
  },
  {
    id: "city-2025",
    name: "سيتي باص",
    yearLabel: "2025",
    seatsLabel: "55 + 1",
    summary:
      "حلول نقل مبتكرة توفر الوقت والجهد وتسهّل التنقل داخل المدينة بأعلى كفاءة.",
    amenities: [
      "نظام كاميرات مراقبة",
      "مقاعد جلد فاخرة",
      "ستائر فاخرة",
      "وسائل السلامة",
      "أنظمة فرامل متقدمة ABS",
      "نظام تحديد المواقع GPS",
      "تكييف مناسب للأجواء",
    ],
    coverImage: "/fleet/city-2025/cover.webp",
    exteriorImages: ["/fleet/city-2025/cover.webp"],
    interiorImages: [],
    images: ["/fleet/city-2025/cover.webp"],
  },
  {
    id: "labour-2024",
    name: "باص العمال",
    yearLabel: "2024",
    seatsLabel: "66 + 1",
    summary:
      "حلول نقل متطورة تضمن الالتزام بالمواعيد وتجربة سفر سلسة لفريق العمل.",
    amenities: [
      "وسائل السلامة",
      "أنظمة فرامل متقدمة ABS",
      "نظام تحديد المواقع GPS",
      "تكييف مناسب للأجواء",
    ],
    coverImage: "/fleet/labour-2024/cover.webp",
    exteriorImages: ["/fleet/labour-2024/cover.webp"],
    interiorImages: [],
    images: ["/fleet/labour-2024/cover.webp"],
  },
  {
    id: "mini-2025-2026",
    name: "ميني باص",
    yearLabel: "2025 – 2026",
    seatsLabel: "55 + 1",
    summary:
      "تنقل بأمان وراحة مع الميني باص العصري والمجهز لأفضل تجربة سفر.",
    amenities: [
      "وسائل السلامة",
      "أنظمة فرامل متقدمة ABS",
      "نظام تحديد المواقع GPS",
      "تكييف مناسب للأجواء",
    ],
    coverImage: "/fleet/mini-2025-2026/cover.webp",
    exteriorImages: ["/fleet/mini-2025-2026/cover.webp"],
    interiorImages: [],
    images: ["/fleet/mini-2025-2026/cover.webp"],
    // TODO(content): brochure page 14 Arabic banner says سيتي باص while English says Mini Bus — confirm with client
    notes: "بانتظار تأكيد التصنيف من العميل",
  },
] as const
