import type { FleetCategory } from "../types"

export const fleet: readonly FleetCategory[] = [
  {
    id: "premium-vip-2026",
    name: "Premium VIP Bus",
    yearLabel: "2026",
    seatsLabel: "18 + 1 + 1",
    summary:
      "Discover the pinnacle of comfort and luxury in our new buses, equipped with massage seats featuring heating and cooling for the ultimate travel experience.",
    amenities: [
      "Massage seats",
      "Cooling seats",
      "Heating seats",
      "USB Type-C charging ports",
      "Wi‑Fi",
      "CCTV system",
      "Sound system",
      "Display screens",
      "Refrigerator",
      "Premium lighting",
      "WC",
      "Luxury curtains",
      "Safety features",
      "ABS systems",
      "GPS systems",
    ],
    coverImage: "/fleet/premium-vip-2026/exterior/pv-col.webp",
    exteriorImages: [
      "/fleet/premium-vip-2026/exterior/pv-out-1.webp",
      "/fleet/premium-vip-2026/exterior/pv-out-2.webp",
      "/fleet/premium-vip-2026/exterior/pv-out-3.webp",
      "/fleet/premium-vip-2026/exterior/pv-out-4.webp",
      "/fleet/premium-vip-2026/exterior/pv-out-5.webp",
      "/fleet/premium-vip-2026/exterior/pv-out-6.webp",
    ],
    interiorImages: [
      "/fleet/premium-vip-2026/interior/pv-in-1.webp",
      "/fleet/premium-vip-2026/interior/pv-in-2.webp",
      "/fleet/premium-vip-2026/interior/pv-in-3.webp",
      "/fleet/premium-vip-2026/interior/pv-in-4.webp",
    ],
    images: ["/fleet/premium-vip-2026/exterior/pv-col.webp"],
    interactive: true,
  },
  {
    id: "vip-2026",
    name: "VIP Bus",
    yearLabel: "2026",
    seatsLabel: "28 + 1 + 1",
    summary:
      "Experience ultimate comfort with our adjustable and movable VIP seats, allowing you to choose the perfect seating position for a truly relaxing journey.",
    amenities: [
      "Luxury VIP seats",
      "Wi‑Fi",
      "CCTV system",
      "USB charging ports",
      "Premium lighting",
      "Refrigerator",
      "Sound system",
      "WC",
      "Display screens",
      "Cooling bus comfort",
      "Luxury curtains",
      "Safety features",
      "ABS systems",
      "GPS systems",
    ],
    coverImage: "/fleet/vip-2026/cover.webp",
    exteriorImages: ["/fleet/vip-2026/cover.webp"],
    interiorImages: [],
    images: ["/fleet/vip-2026/cover.webp"],
  },
  {
    id: "coach-2025-2026",
    name: "Coach Bus",
    yearLabel: "2025 – 2026",
    seatsLabel: "49 + 1 + 1",
    summary:
      "We serve Hajj and Umrah pilgrims with a fleet equipped to the highest standards of quality and safety.",
    amenities: [
      "Luxury leather seats",
      "Wi‑Fi",
      "CCTV system",
      "USB charging ports",
      "Premium lighting",
      "Refrigerator",
      "Sound system",
      "WC",
      "Display screens",
      "Cooling bus comfort",
      "Luxury curtains",
      "Safety features",
      "ABS systems",
      "GPS systems",
    ],
    coverImage: "/fleet/coach-2025-2026/cover.webp",
    exteriorImages: ["/fleet/coach-2025-2026/cover.webp"],
    interiorImages: [],
    images: ["/fleet/coach-2025-2026/cover.webp"],
  },
  {
    id: "city-2024",
    name: "City Bus",
    yearLabel: "2024",
    seatsLabel: "45 + 1",
    summary:
      "A modern transport network designed to meet the city's needs and facilitate passenger movement with high efficiency.",
    amenities: [
      "CCTV system",
      "Luxury leather seats",
      "Luxury curtains",
      "Safety features",
      "ABS systems",
      "GPS systems",
      "Cooling bus comfort",
    ],
    coverImage: "/fleet/city-2024/cover.webp",
    exteriorImages: ["/fleet/city-2024/cover.webp"],
    interiorImages: [],
    images: ["/fleet/city-2024/cover.webp"],
  },
  {
    id: "city-2025",
    name: "City Bus",
    yearLabel: "2025",
    seatsLabel: "55 + 1",
    summary:
      "Innovative transport solutions that save time and effort, making urban mobility highly efficient.",
    amenities: [
      "CCTV system",
      "Luxury leather seats",
      "Luxury curtains",
      "Safety features",
      "ABS systems",
      "GPS systems",
      "Cooling bus comfort",
    ],
    coverImage: "/fleet/city-2025/cover.webp",
    exteriorImages: ["/fleet/city-2025/cover.webp"],
    interiorImages: [],
    images: ["/fleet/city-2025/cover.webp"],
  },
  {
    id: "labour-2024",
    name: "Labour Bus",
    yearLabel: "2024",
    seatsLabel: "66 + 1",
    summary:
      "Advanced transport solutions ensuring punctuality and a seamless travel experience for the workforce.",
    amenities: [
      "Safety features",
      "ABS systems",
      "GPS systems",
      "Cooling bus comfort",
    ],
    coverImage: "/fleet/labour-2024/cover.webp",
    exteriorImages: ["/fleet/labour-2024/cover.webp"],
    interiorImages: [],
    images: ["/fleet/labour-2024/cover.webp"],
  },
  {
    id: "mini-2025-2026",
    name: "Mini Bus",
    yearLabel: "2025 – 2026",
    seatsLabel: "55 + 1",
    summary:
      "Travel safely and comfortably with the modern minibus, equipped for the best travel experience.",
    amenities: [
      "Safety features",
      "ABS systems",
      "GPS systems",
      "Cooling bus comfort",
    ],
    coverImage: "/fleet/mini-2025-2026/cover.webp",
    exteriorImages: ["/fleet/mini-2025-2026/cover.webp"],
    interiorImages: [],
    images: ["/fleet/mini-2025-2026/cover.webp"],
    // TODO(content): brochure page 14 Arabic banner says سيتي باص while English says Mini Bus — confirm with client
    notes: "Awaiting client confirmation of category labeling",
  },
] as const
