/** Alt text for the photos in `photoManifest`, keyed by photo id. Describes what is shown, not where. */
export const photoAlts: Record<string, string> = {
  "exterior-7727": "A white and gold Durrat Almunawwara Co. coach",
  "exterior-7724": "Coaches parked in a row under a shaded canopy",
  "exterior-7725": "Front view of coaches parked under a canopy",
  "exterior-0417": "Aerial view of a coach parked in a yard",
  "exterior-0422": "A large yard with rows of covered bus parking",
  "exterior-0427": "Rows of covered bus parking",
  "exterior-0441": "A line of yellow Durrat Almunawwara Co. buses",
  "interior-0212": "The aisle of a coach with leather seats and soft ceiling lights",
  "interior-0222": "Leather seats with diamond stitching and seat belts",
  "interior-0217": "A headrest embroidered with the Durrat Almunawwara Co. logo",
  "interior-0231": "A row of leather seats with logo headrests",
  "interior-0236": "Close-up of quilted leather seat backing",
  "interior-0269": "The aisle of a coach with beige and grey seats",
  "interior-0274": "Beige and grey seats with the Durrat Almunawwara Co. logo",
  "interior-0283": "The driver's cockpit",
  "interior-0301": "Overhead handrails inside a bus",
  "interior-0396": "Brown leather seats with logo headrests",
  "workshop-0331": "Spare parts on shelving in a warehouse",
  "workshop-0334": "Racks of boxed spare parts",
  "workshop-0358": "Spare tyres and parts stored in a warehouse",
  "workshop-0362": "Stacked tyres and shelves in a warehouse",
  "workshop-0180": "A mechanic servicing a coach",
  "company-0098": "The company signboard at the far end of a gated yard",
  "company-0108": "A gate and signboard of Durrat Almunawwara Co.",
  "company-0113": "Close-up of the Durrat Almunawwara Co. signboard",
  "exterior-0418": "Aerial view of a coach parked next to a grass strip",
  "exterior-0431": "Staff washing a white coach in a covered bay",
  "exterior-0436": "A white coach being washed in a service bay",
  "interior-0213": "A reclined leather seat beside a window",
  "interior-0225": "Side view of a leather seat with a logo headrest",
  "interior-0394": "Two leather seats with logo headrests",
  "workshop-0123": "Two mechanics checking a coach engine from the rear",
  "workshop-0126": "A mechanic reaching into a coach engine bay",
  "workshop-0146": "A mechanic in a cap checking the engine oil level",
  "workshop-0153": "Two mechanics working at the rear of a coach",
  "workshop-0168": "A mechanic working close to the engine",
  "workshop-0205": "Two mechanics standing in front of a coach",
  "workshop-0371": "Technicians repairing equipment inside a coach cabin",
  "workshop-0342": "Two warehouse staff checking stock against a clipboard",
  "company-0444": "The reception desk with the company logo on the wall",
  "company-0449": "Reception desk, flag, and logo wall",
  "company-0454": "A receptionist at the front desk under the company logo",
  "people-0457": "A team member working on a laptop at a desk",
  "people-0463": "A team member working at a desk with a large monitor",
  "people-0467": "A team member in a white thobe working at a computer",
  "people-0475": "A team member at a desk with a microphone and monitor",
  "people-0478": "A team member in a yellow shirt at a computer",
  "people-0486": "A team member in a red polo working at a desk",
  "people-0496": "A team member standing in the office kitchen",
  "people-0505": "A team member in a yellow shirt at a desk with files",
}
