/**
 * Turns the client's original photos into web masters.
 *
 *   node scripts/process-photos.mjs "<path to the photos folder>"
 *
 * One WebP per photo (1920px long edge, EXIF orientation applied, metadata
 * such as GPS stripped). next/image builds the responsive sizes at request
 * time, so only one master per photo is stored. Writes
 * `src/content/photoManifest.ts` with the real pixel sizes.
 */
import { mkdir, writeFile } from "node:fs/promises"
import { readdirSync } from "node:fs"
import path from "node:path"
import sharp from "sharp"

const source = process.argv[2]
if (!source) {
  console.error('Usage: node scripts/process-photos.mjs "<photos folder>"')
  process.exit(1)
}

/** category folder -> photo ids shipped on the site. Faces and plates are allowed (client confirmed). */
const SELECTION = {
  exterior: [
    "IMG_7727", "IMG_7724", "IMG_7725", "IMG_0417", "IMG_0418", "IMG_0422",
    "IMG_0427", "IMG_0441", "IMG_0431", "IMG_0436",
  ],
  interior: [
    "IMG_0212", "IMG_0222", "IMG_0213", "IMG_0217", "IMG_0231", "IMG_0236",
    "IMG_0225", "IMG_0269", "IMG_0274", "IMG_0283", "IMG_0301", "IMG_0394", "IMG_0396",
  ],
  workshop: [
    "IMG_0123", "IMG_0126", "IMG_0146", "IMG_0153", "IMG_0168", "IMG_0205",
    "IMG_0371", "IMG_0342", "IMG_0331", "IMG_0334", "IMG_0358", "IMG_0362", "IMG_0180",
  ],
  company: ["IMG_0098", "IMG_0108", "IMG_0113", "IMG_0444", "IMG_0449", "IMG_0454"],
  people: [
    "IMG_0457", "IMG_0463", "IMG_0467", "IMG_0475",
    "IMG_0478", "IMG_0486", "IMG_0496", "IMG_0505",
  ],
}

const outRoot = path.resolve("public/photos")
const manifest = []

for (const [category, ids] of Object.entries(SELECTION)) {
  const dir = path.join(source, category)
  const files = readdirSync(dir)
  await mkdir(path.join(outRoot, category), { recursive: true })

  for (const id of ids) {
    const file = files.find((f) => f.startsWith(`${id}.`))
    if (!file) throw new Error(`Missing ${category}/${id}`)
    const name = id.replace("IMG_", "")
    const dest = path.join(outRoot, category, `${name}.webp`)
    const info = await sharp(path.join(dir, file))
      .rotate()
      .resize({ width: 1920, height: 1920, fit: "inside", withoutEnlargement: true })
      .webp({ quality: 75 })
      .toFile(dest)
    manifest.push({
      id: `${category}-${name}`,
      category,
      src: `/photos/${category}/${name}.webp`,
      width: info.width,
      height: info.height,
    })
  }
}

const body = `// Generated by scripts/process-photos.mjs. Do not edit by hand.
export type PhotoCategory = "exterior" | "interior" | "workshop" | "company" | "people"

export type PhotoEntry = {
  id: string
  category: PhotoCategory
  src: string
  width: number
  height: number
}

export const photoManifest: readonly PhotoEntry[] = ${JSON.stringify(manifest, null, 2)}
`
await writeFile(path.resolve("src/content/photoManifest.ts"), body)
console.log(`${manifest.length} photos written`)
